---
- name: Download beszel agent deb
  ansible.builtin.get_url:
    url: "{{ beszel_agent_download_url }}"
    dest: /var/tmp/beszel-agent.deb
    mode: '0644'

- name: Check if installer exists
  ansible.builtin.stat:
    path: /var/tmp/beszel-agent.deb
  register: agent_deb_file

- name: Install beszel agent deb
  ansible.builtin.apt:
    deb: /var/tmp/beszel-agent.deb
    state: present
  notify: restart beszel-agent
  when: not ansible_check_mode or agent_deb_file.stat.exists

- name: Check if service unit exists
  ansible.builtin.stat:
    path: /lib/systemd/system/beszel-agent.service
  register: agent_service_file

- name: Create systemd override directory
  ansible.builtin.file:
    path: /etc/systemd/system/beszel-agent.service.d
    state: directory
    mode: '0755'

- name: Configure beszel agent environment variables
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/beszel-agent.service.d/override.conf
    mode: '0644'
  notify: restart beszel-agent

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start beszel agent service
  ansible.builtin.systemd:
    name: beszel-agent
    state: started
    enabled: true
  when: not ansible_check_mode or agent_service_file.stat.exists
