---
- name: Include install tasks
  ansible.builtin.include_tasks: install.yml
  when: beszel_agent_state == 'present'

- name: Include uninstall tasks
  ansible.builtin.include_tasks: uninstall.yml
  when: beszel_agent_state == 'absent'