beszel_agent_port: 45876
beszel_agent_key: "{{ lookup('env', 'BESZEL_AGENT_KEY') }}"
beszel_agent_token: "{{ lookup('env', 'BESZEL_AGENT_TOKEN') }}"
beszel_agent_hub_url: "{{ lookup('env', 'BESZEL_AGENT_HUB_URL') }}"
beszel_agent_state: "present"
beszel_agent_version: "0.17.0"
beszel_agent_arch: "amd64"
beszel_agent_platform: "linux"
beszel_agent_download_url: "https://github.com/henrygd/beszel/releases/download/v{{ beszel_agent_version }}/beszel-agent_{{ beszel_agent_version }}_{{ beszel_agent_platform }}_{{ beszel_agent_arch }}.deb"